// pending units

Pending Units = COUNTROWS( // count the number of rows that are 'Pending' in table 'BIM360_Members' column [Status]
    FILTER(
        RELATEDTABLE(BIM360_Members),
        BIM360_Members[Status]="Pending"
        )
    )
