Consuming License = COUNTROWS( // count the number of rows that are 'Pending' or 'Active' in table 'BIM360_Members' column [Status]
    FILTER(
        RELATEDTABLE(BIM360_Members),
        BIM360_Members[Status]="Pending" || BIM360_Members[Status]="Active"
        )
    )
