Disabled Members = COUNTROWS( // count the number of rows that are 'Inactive-Disabled' in table 'BIM360_Members' column [Status]
    FILTER(
        RELATEDTABLE(BIM360_Members),
        BIM360_Members[Status]="Inactive-Disabled"
        )
    )
