Spare Licenses = // available - count of emails filtered for active OR pending (note active AND pending would be different)

SUM( // only a single row in this table so could equally use min or max
    'BIM360_Service_Levels'[DocsAvailable]
    )

-

COUNTROWS( // count the number of rows that are 'Pending' or 'Active' in table 'BIM360_Members' column [Status]
    FILTER(
        RELATEDTABLE(BIM360_Members),
        BIM360_Members[Status]="Pending" || BIM360_Members[Status]="Active"
        )
    )
